### ISSUE TITLE
Preview scene.xml 

### ISSUE THREAD

**Issue by zichunxx** [gemcollector/maniwhere#5]
Hi, zhecheng!

How do you preview related mujoco XML scenes onscreen? 

I'm used to previewing scenes with the mujoco's `simulate` binary, but this method will trigger some path errors with your XML scenes. 

These path-related errors I'm encountering don't affect the program's operation. I think I'm using a different way of previewing scenes from yours.

BTW, my mujoco version is 3.0.1.

Thanks!

**Comment by gemcollector** [comment]
Hi, there. yea, you can not directly visualize the whole scene due to the path relation. How we construct these environments is to put all `xml` and mesh files under the same folder. For modularizing each component, we split them into different parts. Then we can easily switch to different robots and scenes.

**Comment by gemcollector** [comment]
No, When create these tasks, we will put them on the same folder, and render them via mujoco viewer to see whether the setup is correct.
