### ISSUE TITLE
difficulties in constructing new task environment

### ISSUE THREAD

**Issue by zlm200** [gemcollector/maniwhere#7]
I'm interested in applying your methods to the Sawyer robot but am facing some challenges in setting up the task environment. I already have the robot's model but am struggling to write JSON files similar to those found in maniwhere/envs/configs and Python files used for task implementation. Could you provide any reference materials or examples? I'm not sure how to proceed with the modifications required and would greatly appreciate your advice.

**Comment by gemcollector** [comment]
Yea...since we want to separate each module for reusability, this makes adding new tasks relatively complex. If you're considering adding new tasks, I recommend using the existing robots we have. Otherwise, it would still require a significant amount of work. This not only necessitates a good familiarity with our codebase but also a solid understanding of Mujoco. I might suggest that you first learn how to use Mujoco and dm-control, then our environments might be more accessible for you to read.

**Comment by zlm200** [comment]
Sure, thank you for your reply. I will consider your suggestion.
